name: Main

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable

    - name: Setup GLFW dependencies
      run: sudo apt install xorg-dev --yes

    - name: Setup haxe
      uses: haxeui/haxeui-core/.github/actions/haxe@master
      with:
        haxe-version: 4.1.1

    - name: Setup haxe dependencies
      run: haxelib install hxcpp

    - name: Test samples
      run: haxe build_all.hxml
