name: Main

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable

    - name: Setup GLFW dependencies
      run: sudo apt install xorg-dev --yes

    - name: Setup haxe
      uses: haxeui/haxeui-core/.github/actions/haxe@master
      with:
        haxe-version: 4.1.1

    - name: Setup haxe dependencies
      run: haxelib install hxcpp

    - name: Setup precompiled shaderc library
      run: |
        curl https://storage.googleapis.com/shaderc/artifacts/prod/graphics_shader_compiler/shaderc/linux/continuous_clang_release/310/20200616-232648/install.tgz --output install.tgz
        tar xf install.tgz
        mkdir libs/hxshaderc/build
        cp install/lib/libshaderc_combined.a libs/hxshaderc/build/libshaderc_combined.a
        echo caa519ca532a6a3a0279509fce2ceb791c4f4651 > libs/hxshaderc/build/hash.txt

    - name: Test samples
      run: |
        haxe cppia_host.hxml
        haxe build_all.hxml
